---
- name: "Download wordpress installation"
  ansible.builtin.get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz
  tags: [download_wp, one_time]
- name: "Uncompress wordpress installation"
  ansible.builtin.unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www
    remote_src: yes
  become: yes
  tags: [uncrompress_wp, one_time]
- name: "Copy wordpress base config file"
  ansible.builtin.copy:
    src: "{{ wp_installation_dir }}/wp-config-sample.php"
    dest: "{{ wp_installation_dir }}/wp-config.php"
    remote_src: yes
  become: yes
  tags: [cp_wp_config, one_time]
- name: "Set wp variables in conf file"
  ansible.builtin.replace:
    path: "{{ wp_installation_dir }}/wp-config.php"
    regexp: "{{ item.regex }}"
    replace: "{{ item.value }}"
  with_items:
    - { regex: "database_name_here", value: "{{ wp_db_name }}" }
    - { regex: "username_here", value: "{{ wp_db_user }}" }
    - { regex: "password_here", value: "{{ wp_db_pass }}" }
    - { regex: "localhost", value: "{{ wp_db_ip }}" }
  tags: [set_wp_variables, one_time]
  become: yes
