---
- hosts: all
  tasks:
    - name: 'Update APT database'
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: yes
    - name: 'Install system packages dependencies'
      apt: 
        name: "{{ item }}"
        state: latest
      become: yes
      with_items:
        - php
        - apache2
        - libapache2-mod-php
        - php-gd
        - mysql-server
        - python-mysqldb
        - php-mysql